
import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'ai-fashion-moodboard',
    title: 'AI Fashion Moodboard',
    category: 'Neural Branding',
    model: 'Gemini 3 + Nano Banana Pro',
    description: 'A lightweight web app that generates structured fashion moodboards from text prompts and allows targeted image refinement.',
    imageUrl: '/assets/moodboard-project.jpg',
    githubUrl: 'https://github.com/margaretmz/ai-fashion-moodboard',
    mediumUrl: 'https://medium.com/google-developer-experts/fashion-moodboard-with-gemini-3-nano-banana-pro-0d5bfd54a557',
    youtubeUrl: 'https://youtu.be/Sn_YHvtRNzM',
    technicalArchitecture: 'Using Gemini 3 for structured data extraction and Nano Banana Pro for localized image editing capabilities.',
    stack: ['Gemini 3', 'Nano Banana Pro'],
    status: 'published'
  },
  {
    id: 'ai-fashion-house',
    title: 'AI Fashion House',
    category: 'Agentic Workflow',
    model: 'Multi-Agent System',
    description: 'Automates the entire creative pipeline—from conceptualizing ideas and historical research to high-fidelity media production.',
    imageUrl: '/assets/ai-fashion-house-project.jpg',
    githubUrl: 'https://github.com/margaretmz/ai-fashion-house',
    mediumUrl: 'https://medium.com/google-cloud/ai-fashion-house-adk-google-cloud-d12983cd3393',
    youtubeUrl: 'https://youtu.be/7Gjd4UN0PpQ',
    technicalArchitecture: 'Multi-agent orchestration using Google Cloud and high-fidelity video generation for couture visualization.',
    stack: ['Vertex AI', 'Multi-Agent SDK', 'Google Cloud'],
    status: 'published'
  },
  {
    id: 'sketch2runway',
    title: 'Fashion Sketch2Runway',
    category: 'Motion Synthesis',
    model: 'Gemini 2.0 Flash + Veo 3',
    description: 'Converts fashion sketches into high-fidelity photos and transforms them into stunning cinematic runway videos.',
    imageUrl: '/assets/sketch2runway-project.jpg',
    githubUrl: 'https://github.com/margaretmz/sketch2runway',
    mediumUrl: 'https://medium.com/google-developer-experts/fashion-sketch2runway-with-gemini2flash-veo3-ced1e2776fea',
    youtubeUrl: 'https://youtu.be/9Bo5sEVoVQk',
    technicalArchitecture: 'Leverages Gemini 2.0 Flash for image reasoning and Veo 3 for temporally consistent video generation from static frames.',
    stack: ['Gemini 2.0 Flash', 'Veo 3', 'Python', 'Flask'],
    status: 'published'
  },
  {
    id: 'century-style',
    title: 'Century of Style',
    category: 'Historical Synthesis',
    model: 'Imagen 4 + Veo 3',
    description: 'A collection of ten looks spanning 1920s to 2010s, teaching fashion history through AI-generated motion visuals.',
    imageUrl: '/assets/century-of-style-project.jpg',
    githubUrl: '#',
    mediumUrl: 'https://margaretmz.medium.com/century-of-style-100-years-of-fashion-in-motion-3ada00f4c585',
    youtubeUrl: 'https://youtu.be/Sj8K_8cTuYI',
    technicalArchitecture: 'Visual consistency maintained across decades by prompting with specific material and silhouette constraints.',
    stack: ['Imagen 4', 'Nano Banana', 'Veo 3'],
    status: 'published'
  },
  {
    id: 'ai-fashion-designs',
    title: 'AI Fashion Designs',
    category: 'Digital Showcase',
    model: 'Neural Generative Art',
    description: 'A curated showcase of experimental AI fashion designs explored through various generative systems.',
    imageUrl: '/assets/machine2art.jpg',
    githubUrl: '#',
    mediumUrl: '#',
    youtubeUrl: 'https://www.youtube.com/@Machine2Art',
    technicalArchitecture: 'Exploring the latent space of textile patterns and runway aesthetics.',
    stack: ['Google GenMedia', 'Midjourney', 'Krea.ai'],
    status: 'published'
  },
  {
    id: 'parsons-design',
    title: 'Design at Parsons',
    category: 'Educational',
    model: 'Creative Direction',
    description: 'Exploration of motion, fashion, and graphic design at Parsons, including the "Funny Face" Title Sequence.',
    imageUrl: '/assets/funny-face-project.jpg',
    githubUrl: '#',
    mediumUrl: '#',
    youtubeUrl: 'https://youtu.be/fImRNPE0Wko',
    technicalArchitecture: 'Traditional design methodology integrated with modern motion graphics workflows.',
    stack: ['After Effects', 'Illustrator', 'Photoshop', 'InDesign', 'Fashion Design', 'Graphic Design', 'Motion Design'],
    status: 'published'
  },
  {
    id: 'project-koru',
    title: 'Project Koru',
    category: 'Edge AI',
    model: 'Real-time Race Coach',
    description: 'A real-time, offline AI race coach developed for the Google AI Sprint 2025.',
    imageUrl: '/assets/project-koru.jpg',
    githubUrl: 'https://github.com/gemini-fieldtest',
    mediumUrl: 'https://www.linkedin.com/posts/googledevelopers_architect-high-velocity-agents-that-verify-activity-7422687111570628608-BC1y',
    youtubeUrl: 'https://youtube.com/shorts/2ZWElKj3k1I',
    technicalArchitecture: 'Edge deployment of lightweight models for low-latency biometric feedback and telemetry analysis.',
    stack: ['Gemini Pro', 'Gemini Nano', 'Edge Devices', 'Antigravity', 'Google AI Studio'],
    status: 'published'
  },
  {
    id: 'google-early-access',
    title: 'Google AI Early Access',
    category: 'Advocacy',
    model: 'Product Testing',
    description: 'GDE early access testing for Gemini, Nano Banana, Imagen, and Veo product iterations.',
    imageUrl: '/assets/google-ai-early-access.jpg',
    githubUrl: '#',
    mediumUrl: '#',
    youtubeUrl: 'https://www.youtube.com/playlist?list=PLHNG87hddcLrIiKKzal9xbdNLEhKYF7tl',
    technicalArchitecture: 'Field testing and providing critical feedback on model reasoning and visual fidelity during private beta stages.',
    stack: ['Gemini Ecosystem', 'Nano Banana Pro', 'Veo', 'Imagen'],
    status: 'published'
  },
  {
    id: 'ai-community-summit',
    title: 'AI Community Summit',
    category: 'Community',
    model: 'Public Speaking',
    description: 'Speaking at the AI Community Summit in Bali on AI Fashion House & Sketch2Runway deep dives.',
    imageUrl: '/assets/2025-ai-community-summit.jpg',
    githubUrl: '#',
    mediumUrl: '#',
    youtubeUrl: 'https://www.youtube.com/playlist?list=PLHNG87hddcLrIiKKzal9xbdNLEhKYF7tl',
    technicalArchitecture: 'Disseminating research findings to the global developer community through technical deep-dives.',
    stack: ['GDE', 'Public Speaking', 'Community'],
    status: 'published'
  }
];
